# This file is generated by the Geant4 CMake buildsystem and should not be editted
#
# This file stores paths and settings to external libraries found and used by this
# install of Geant4 when it was built.

macro(geant4_set_and_check_package_variable _name _value _type _docstring)
  if(DEFINED ${_name})
    if(NOT ("${${_name}}" STREQUAL "${_value}"))
      message(WARNING "Value of '${_name}' is already set and does not match value set at Geant4 build-time")
    endif()
  else()
    set(${_name} ${_value} CACHE ${_type} "${_docstring}")
  endif()
endmacro()


# CLHEP Build Time Settings
geant4_set_and_check_package_variable(CLHEP_DIR "/home/g4test/Geant4.11.1.p01/install-clhep/lib/CLHEP-2.4.6.2" PATH "The directory containing a CMake configuration file for CLHEP.")

# EXPAT Build Time Settings
geant4_set_and_check_package_variable(EXPAT_INCLUDE_DIR "/usr/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(EXPAT_LIBRARY "/usr/lib/x86_64-linux-gnu/libexpat.so" FILEPATH "Path to a library.")

# TBB Build Time Settings

# Qt5 Build Time Settings
geant4_set_and_check_package_variable(Qt5Core_DIR "/usr/lib/x86_64-linux-gnu/cmake/Qt5Core" PATH "The directory containing a CMake configuration file for Qt5Core.")
geant4_set_and_check_package_variable(Qt5Gui_DIR "/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui" PATH "The directory containing a CMake configuration file for Qt5Gui.")
geant4_set_and_check_package_variable(Qt5Widgets_DIR "/usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets" PATH "The directory containing a CMake configuration file for Qt5Widgets.")
geant4_set_and_check_package_variable(Qt5OpenGL_DIR "/usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL" PATH "The directory containing a CMake configuration file for Qt5OpenGL.")
geant4_set_and_check_package_variable(Qt5PrintSupport_DIR "/usr/lib/x86_64-linux-gnu/cmake/Qt5PrintSupport" PATH "The directory containing a CMake configuration file for Qt5PrintSupport.")

# OpenGL Build Time Settings
geant4_set_and_check_package_variable(OPENGL_INCLUDE_DIR "/usr/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(OPENGL_gl_LIBRARY "/usr/lib/x86_64-linux-gnu/libGL.so" FILEPATH "Path to a library.")
